name: LeadByExperience
favicon: null
layout_spectrum: 0.3201299952343106
typography_spectrum: 0.9490146259777248
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6505014442373067
  lightness: 0.7298620890360326
  saturation: 0.5258900711778551
  rhythmicContrast: 0.7974781482480466
purpose: []
